name: PR Checks

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  title_check:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check PR Title Prefix
      id: title_check
      uses: actions/github-script@v5
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const titleRegex = /^(fix|feat|test):/;
          const prTitle = github.context.payload.pull_request.title;
          
          if (!titleRegex.test(prTitle)) {
            core.setFailed('PR title must start with "fix:", "feat:", or "test:"');
          }

